
services:

  postgres:
    container_name: postgres
    image: postgres:latest
    entrypoint:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - main
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - posgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn library.wsgi -b 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/code/
    depends_on:
      - postgres
    expose:
      - "8000"
    networks:
      - main
    restart: always

  nginx:
    container_name: nginx
    command: nginx -g 'deamon off;'
    depends_on:
      - app
    image: nginx:latest
    networks:
      - main
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  main:

volumes:
  posgres_data:
