# Generated by Django 4.0.4 on 2022-06-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='inventory',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
