# Generated by Django 4.0.4 on 2022-06-10 14:28

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_alter_book_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrow',
            name='barrow_time',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
        migrations.AlterField(
            model_name='barrow',
            name='barrow_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='barrow',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
