# Generated by Django 4.0.4 on 2022-06-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0005_alter_book_author_alter_book_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barrow',
            old_name='barrow_time',
            new_name='barrow_days',
        ),
        migrations.AlterField(
            model_name='barrow',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
