# Generated by Django 4.0.4 on 2022-06-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0006_rename_barrow_time_barrow_barrow_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrow',
            name='barrow_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
    ]
