# Generated by Django 4.0.4 on 2022-06-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0008_barrowaction_delete_barrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='inventory',
        ),
    ]
